name: Release

on:
  create:
    tags:
      - v*

jobs:
  server:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20.2
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.2
        id: go

      - name: Check out branch
        uses: actions/checkout@v2

      - name: Build On Linux 32
        run: |
          go build -trimpath -o ercpow/ercpow_386 main.go
          chmod +x ercpow/ercpow_386
        env:
          GOOS: linux
          GOARCH: 386

      - name: Build On Linux 64
        run: |
          go build -trimpath -o ercpow/ercpow_amd64 main.go
          chmod +x ercpow/ercpow_amd64
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Build On Linux arm32
        run: |
          go build -trimpath -o ercpow/ercpow_arm main.go
          chmod +x ercpow/ercpow_arm
        env:
          GOOS: linux
          GOARCH: arm

      - name: Build On Linux arm64
        run: |
          go build -trimpath -o ercpow/ercpow_arm64 main.go
          chmod +x ercpow/ercpow_arm64
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Build On Linux mips
        run: |
          go build -trimpath -o ercpow/ercpow_mips main.go
          chmod +x ercpow/ercpow_mips
        env:
          GOOS: linux
          GOARCH: mips

      - name: Build On Darwin
        run: |
          go build -trimpath -o ercpow/ercpow_darwin main.go
          chmod +x ercpow/ercpow_darwin
        env:
          GOOS: darwin
          GOARCH: amd64

      - name: Build On Windows 64
        run: |
          go build -trimpath -o ercpow/ercpow_64.exe main.go
        env:
          GOOS: windows
          GOARCH: amd64

      - name: Build On Windows 32
        run: |
          go build -trimpath -o ercpow/ercpow_32.exe main.go
        env:
          GOOS: windows
          GOARCH: 386

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: ercpow/*
          fail_on_unmatched_files: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          append_body: true